### ISSUE TITLE
Atom BIFs

### ISSUE THREAD

**Issue by KronicDeth** [GetFirefly/firefly#129]
- [x] Atoms
    - [x] `atom_to_binary/2` (#21)
    - [x] `atom_to_list/1` (#21)
    - [x] `is_atom/1` (#21)
    - [x] `list_to_atom/1` (#52)
    - [x] `list_to_existing_atom/1` (#53)
