### ISSUE TITLE
Binary BIFs

### ISSUE THREAD

**Issue by KronicDeth** [GetFirefly/firefly#130]
- [x] Binaries
    - [x] `bit_size/1` (#21)
    - [x] `bitstring_to_list/1` (#21)
    - [x] `binary_part/2`(#70)
    - [x] `binary_part/3` (#21)
    - [x] `byte_size/1` (#21)
    - [x] `is_binary/1` (#21)
    - [x] `is_bitstring/1` (#71)
    - [x] `list_to_binary/1` (#72)
    - [x] `list_to_bitstring/1` (#74)
    - [x] `split_binary/2` (#76)
    - [x] Parsing to Term
      - [x] `binary_to_atom/2`  (#21)
      - [x] `binary_to_existing_atom/2` (#21)
      - [x] `binary_to_float/1` (#21)
      - [x] `binary_to_integer/1` (#21)
      - [x] `binary_to_integer/2` (#21)
      - [x] `binary_to_list/1` (#21)
      - [x] `binary_to_list/3` (#21)
