### ISSUE TITLE
Comparison BIFs

### ISSUE THREAD

**Issue by KronicDeth** [GetFirefly/firefly#132]
- [x] `/=/2` (#93 as `are_not_equal_after_conversion_2`)
- [x] `</2` (#94 as `is_less_than_2`)
- [x] `=/=/2` (#91 as `are_exactly_not_equal_2`)
- [x] `=:=/2` (#90 as `are_exactly_equal_2`)
- [x] `=</2` (#97 as `is_equal_or_less_than_2`)
- [x] `==/2` (#92 as `are_equal_after_conversion_2`)
- [x] `>/2` (#95 as `is_greater_than_2`)
- [x] `>=/2` (#96 as `is_greater_than_or_equal_2`)
- [x] `min/2` (#98)
- [x] `max/2` (#99)
